name: ac-ehiclip-0.1
channels:
  - conda-forge
  - bioconda
  - r

dependencies:
  - pigz=2.3.4
  - fastqc=0.11.8
  - cutadapt=2.6
  - bowtie2=1.2.3
  - star=2.7.3a
  - bedtools=2.28.0
  - umi_tools=1.0.1
  - ucsc-bedsort=377
  - sambamba=0.7.1
  - samtools=1.9
  - pysam